nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials : true
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': 
            origin_regex: true
            allow_credentials : true
            allow_origin: []
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization',"Allow-Origin-With-Credentials", "Access-Control-Allow-Origin"]
            expose_headers: ['Link']
            max_age: 3600
            
